import { NextResponse, type NextRequest } from "next/server";
import { requireOwnerOrManager, jsonError } from "@/lib/api-auth";
import { getAdminDb } from "@/lib/firebase-admin";
import { Collections } from "@/lib/collections";
import { INVITABLE_ROLES } from "@/lib/roles";
import { appUrl } from "@/lib/stripe-server";
import type { OrgInvite, UserRole } from "@/lib/types";

/**
 * POST /api/invites — invites somebody to join the caller's organization.
 *
 * This is what replaces running scripts/link-user-to-org.ts from a laptop every
 * time a manager hires somebody. Joining an existing organization can never be a
 * client-side write: the rules only allow a profile to be created into an org
 * that does not exist yet, precisely so a signup cannot walk into someone else's
 * portfolio.
 *
 * The document id is the invite token. It is generated by Firestore, so it is
 * unguessable, and it goes in the link. Possession of the link is deliberately
 * not sufficient to accept — see api/invites/accept.
 */

const INVITE_TTL_DAYS = 14;

/** Roles that can be invited, and what each additionally requires. */
function validateRole(
  role: UserRole,
  tenantId?: string,
  vendorId?: string
): string | null {
  if (INVITABLE_ROLES.includes(role)) return null;
  if (role === "tenant") {
    return tenantId ? null : "Inviting a tenant requires the tenant record they belong to";
  }
  if (role === "contractor") {
    return vendorId ? null : "Inviting a contractor requires the vendor record they belong to";
  }
  return `${role} accounts cannot be invited`;
}

export async function POST(req: NextRequest) {
  const guard = await requireOwnerOrManager(req);
  if (!guard.ok) return guard.response;
  const { caller } = guard;
  const orgId = caller.profile.orgId;

  let body: Record<string, unknown>;
  try {
    body = await req.json();
  } catch {
    return jsonError("Expected a JSON body", 400);
  }

  const email = String(body.email ?? "").trim().toLowerCase();
  const role = String(body.role ?? "manager") as UserRole;
  const tenantId = body.tenantId ? String(body.tenantId) : undefined;
  const vendorId = body.vendorId ? String(body.vendorId) : undefined;

  if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) {
    return jsonError("Enter a valid email address", 400);
  }

  const roleError = validateRole(role, tenantId, vendorId);
  if (roleError) return jsonError(roleError, 400);

  const db = await getAdminDb();

  const orgSnap = await db.collection(Collections.ORGANIZATIONS).doc(orgId).get();
  if (!orgSnap.exists) {
    return jsonError("Your organization is not set up yet", 409);
  }

  // The linked record has to belong to this org, or an invite would hand a
  // stranger the lease of somebody in a different portfolio.
  for (const [collection, id] of [
    [Collections.TENANTS, tenantId],
    [Collections.VENDORS, vendorId],
  ] as const) {
    if (!id) continue;
    const snap = await db.collection(collection).doc(id).get();
    if (!snap.exists || snap.data()?.orgId !== orgId) {
      return jsonError("That record does not belong to your organization", 400);
    }
  }

  // Re-inviting the same person replaces the old invite rather than stacking up
  // several live tokens for one address.
  const existing = await db
    .collection(Collections.INVITES)
    .where("orgId", "==", orgId)
    .where("email", "==", email)
    .where("status", "==", "pending")
    .get();
  await Promise.all(
    existing.docs.map((d) => d.ref.update({ status: "revoked" }))
  );

  const now = new Date();
  const ref = db.collection(Collections.INVITES).doc();
  const invite: OrgInvite = {
    id: ref.id,
    orgId,
    orgName: (orgSnap.data()?.name as string) ?? orgId,
    email,
    role,
    status: "pending",
    invitedBy: caller.uid,
    invitedByName: caller.displayName,
    ...(tenantId ? { tenantId } : {}),
    ...(vendorId ? { vendorId } : {}),
    createdAt: now.toISOString(),
    expiresAt: new Date(
      now.getTime() + INVITE_TTL_DAYS * 24 * 60 * 60 * 1000
    ).toISOString(),
  };

  await ref.set(invite);

  console.log(`[invites] ${caller.email} invited ${email} to ${orgId} as ${role}`);

  // No mail is sent from here — RentOS has no mail transport wired up yet, and
  // pretending otherwise would leave invites silently undelivered. The caller
  // gets the link to send themselves.
  return NextResponse.json(
    { invite, acceptUrl: appUrl(`/invite/${ref.id}`) },
    { status: 201 }
  );
}
